:encoder:
    :command: oggenc -Q -b 128 - -o -
    :mime: application/ogg
:decoders:
    mp3: lame --quiet --decode "$fn" -
    flac: flac -d -c -s "$fn"
    ogg: oggdec -Q "$fn" -o -
:library:
    :path: /srv/music/
    :glob: "**/*.{mp3,flac,ogg}"

