:encoder:
    :command: oggenc --quiet -b 128 - -o -
    :mime: application/ogg
:decoders:
    mp3: lame --quiet --decode "$fn" -
    flac: flac -d -c -s "$fn"
:library:
    :path: /srv/music/
    :glob: "**/*.{mp3,flac}"

