#!/usr/bin/env bash

if [ "`whoami`" != "root" ]
then
    echo You are not root
    exit 1
fi

execute() {
    echo $1
    $1
}

TARGET_DIR=~tapefm/app

execute "systemctl stop tapefm"
execute "rm -rf $TARGET_DIR/*"

for fn in `find -type f -not -path '*/\.*'` ; do
    execute "install -D -o tapefm -g tapefm -m 644 $fn $TARGET_DIR/${fn:2}"
done

execute "systemctl start tapefm"
